data:extend({
  {
    type = "fluid",
    name = "liquid-chocolate",
    icon = "__base__/graphics/icons/fluid/crude-oil.png",
    icon_size = 64,
    default_temperature = 25,
    base_color = {r = 0.4, g = 0.2, b = 0.1},
    flow_color = {r = 0.5, g = 0.3, b = 0.2},
    subgroup = "fluid",
    order = "a[liquid-chocolate]",
  },
  {
    type = "fluid",
    name = "mint-oil",
    icon = "__base__/graphics/icons/fluid/lubricant.png",
    icon_size = 64,
    default_temperature = 25,
    base_color = {r = 0.2, g = 0.8, b = 0.4},
    flow_color = {r = 0.3, g = 0.9, b = 0.5},
    subgroup = "fluid",
    order = "a[mint-oil]",
  },
  {
    type = "fluid",
    name = "candy-solvent",
    icon = "__base__/graphics/icons/fluid/heavy-oil.png",
    icon_size = 64,
    default_temperature = 25,
    base_color = {r = 0.4, g = 0.9, b = 0.6},
    flow_color = {r = 0.5, g = 1.0, b = 0.7},
    subgroup = "fluid",
    order = "a[candy-solvent]",
  },
})
